name: Build and Test Python Package

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: polyops
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Build and Install Package
      run: |
        python -m pip install --upgrade pip
        pip install ./polyops
    - name: Run Tests
      run: |
        python -m polyops.tests.btest
